import mongoose from 'mongoose';
import { User } from '../models/User.js';
import { Category } from '../models/Category.js';
import { Vehicle } from '../models/Vehicle.js';
import { Listing } from '../models/Listing.js';
import { WantedPart } from '../models/WantedPart.js';
import { Review } from '../models/Review.js';
import { Order } from '../models/Order.js';
import { Notification } from '../models/Notification.js';
import { sampleCategories, sampleVehicles } from './seedData.js';

export const seedDatabase = async () => {
  try {
    console.log('Clearing old collections and seeding fresh vintage automotive catalog...');
    await Promise.all([
      User.deleteMany({}),
      Category.deleteMany({}),
      Vehicle.deleteMany({}),
      Listing.deleteMany({}),
      WantedPart.deleteMany({}),
      Review.deleteMany({}),
      Order.deleteMany({}),
      Notification.deleteMany({}),
    ]);

    // 1. Create Users
    console.log('Creating demo users and vintage restorers...');
    const admin = await User.create({
      name: 'Retro Parts Admin',
      email: 'admin@retroparts.com',
      password: 'password123',
      phone: '+91 98765 43210',
      role: 'admin',
      bio: 'Retro Parts Core Platform Administration & Catalog Quality Team.',
      location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560001' },
      isVerifiedSeller: true,
      verificationStatus: 'verified',
    });

    const seller = await User.create({
      name: 'Rajesh Vintage Garage',
      email: 'seller@retroparts.com',
      password: 'password123',
      phone: '+91 98450 11223',
      role: 'seller',
      bio: 'Restorer & stockist specializing in classic Honda, Yamaha 2-stroke, Maruti SS80 and Premier original OEM spares.',
      location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
      isVerifiedSeller: true,
      verificationStatus: 'verified',
      sellerRating: 4.9,
      sellerReviewCount: 42,
    });

    const sellerAnand = await User.create({
      name: 'Anand Classic Spares',
      email: 'anand.classicspares@outlook.com',
      password: 'password123',
      phone: '+91 98220 55443',
      role: 'seller',
      bio: 'Stockist of rare NOS parts for Maruti SS80, Zen, Premier Padmini, and Contessa Classic.',
      location: { city: 'Pune', state: 'Maharashtra', pincode: '411004' },
      isVerifiedSeller: true,
      verificationStatus: 'verified',
      sellerRating: 4.8,
      sellerReviewCount: 28,
    });

    const customer = await User.create({
      name: 'Kavita Sharma',
      email: 'user@retroparts.com',
      password: 'password123',
      phone: '+91 97690 99881',
      role: 'buyer',
      bio: 'Restoring a 1989 Yamaha RX100 and a 1998 Honda City 1.5 EXi.',
      location: { city: 'Mumbai', state: 'Maharashtra', pincode: '400050' },
      isVerifiedSeller: false,
      verificationStatus: 'unverified',
    });

    // 2. Create Categories & Vehicles
    console.log('Creating categories and vehicle compatibility models...');
    const createdCategories = await Category.insertMany(sampleCategories);
    const createdVehicles = await Vehicle.insertMany(sampleVehicles);

    const getCat = (slug: string) => {
      const found = createdCategories.find((c) => c.slug === slug);
      return found ? found._id : createdCategories[0]._id;
    };

    // 3. Create Authentic Listings with 100% Real Component Photography
    console.log('Populating authentic vintage parts listings with real component photography...');
    const listings = await Listing.insertMany([
      {
        title: 'Yamaha RX100 Original Mikuni VM20 Slide Carburetor (Made in Japan NOS)',
        description:
          'Authentic Japanese-manufactured Mikuni 20mm round slide carburetor for Yamaha RX100 (1985-1996 models). Stamped with authentic "MIKUNI CORP. JAPAN" on the body. Flange mount, original brass main jet (#115), pilot jet (#22.5), slide and needle intact in factory preservative oil coating.',
        category: getCat('engine-parts'),
        categoryName: 'Engine Parts',
        vehicleBrand: 'Yamaha',
        vehicleModel: 'RX100',
        vehicleYear: 1989,
        vehicleVariant: 'Standard 98cc',
        compatibleVehicles: [
          { brand: 'Yamaha', model: 'RX100', yearFrom: 1985, yearTo: 1996, variant: 'All Variants' },
          { brand: 'Yamaha', model: 'RXG', yearFrom: 1996, yearTo: 1998, variant: '135cc' },
        ],
        oemNumber: '17G-14101-00-JP',
        condition: 'NOS (New Old Stock)',
        partType: 'OEM Original',
        price: 8500,
        originalPrice: 10500,
        quantity: 3,
        negotiable: false,
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
        images: [
          '/parts/carburetor.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: true,
        views: 342,
        rarity: 'Collector Grade',
        shippingAvailable: true,
        shippingCost: 0,
      },
      {
        title: 'NGK Laser Iridium Performance Spark Plug Set (Pack of 4)',
        description:
          'High-performance NGK Laser Iridium fine-wire spark plugs (BPR6EIX) with trivalent metal plating for anti-corrosion and anti-seizing. Precision laser-welded iridium center electrode tip ensures high durability and consistently stable spark for vintage performance engines.',
        category: getCat('electrical-ignition'),
        categoryName: 'Electrical & Ignition',
        vehicleBrand: 'Honda',
        vehicleModel: 'City Type-Z',
        vehicleYear: 2000,
        vehicleVariant: '1.5 VTEC',
        compatibleVehicles: [
          { brand: 'Honda', model: 'City Type-Z', yearFrom: 1998, yearTo: 2003, variant: '1.3, 1.5 EXi, 1.5 VTEC' },
          { brand: 'Maruti Suzuki', model: '800 (SS80)', yearFrom: 1983, yearTo: 2014, variant: 'All Variants' },
          { brand: 'Maruti Suzuki', model: 'Zen (Carbon/Steel)', yearFrom: 1993, yearTo: 2006, variant: 'All Variants' },
          { brand: 'Yamaha', model: 'RX100', yearFrom: 1985, yearTo: 1996, variant: 'All Variants' },
        ],
        oemNumber: 'NGK-BPR6EIX-4PK',
        condition: 'NOS (New Old Stock)',
        partType: 'Period Aftermarket',
        price: 2400,
        originalPrice: 3000,
        quantity: 8,
        negotiable: false,
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
        images: [
          '/parts/spark-plug.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: true,
        views: 450,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 0,
      },
      {
        title: 'Yamaha RX100 Original Yenkay Speedometer & Gauge Cluster (Made in Japan Escorts NOS)',
        description:
          'Original factory-spec Yenkay / Escorts speedometer and gauge assembly for 1985-1996 Yamaha RX100. Crisp white 120 km/h dial, original green neutral & high beam indicator lenses, odometer reset knob, and factory wiring harness coupler. Preserved in original packaging with zero dial fading.',
        category: getCat('lighting-gauges'),
        categoryName: 'Lighting & Gauges',
        vehicleBrand: 'Yamaha',
        vehicleModel: 'RX100',
        vehicleYear: 1989,
        vehicleVariant: 'Standard 98cc',
        compatibleVehicles: [
          { brand: 'Yamaha', model: 'RX100', yearFrom: 1985, yearTo: 1996, variant: 'All Variants' },
          { brand: 'Yamaha', model: 'RX135', yearFrom: 1997, yearTo: 2003, variant: '4-Speed' },
          { brand: 'Yamaha', model: 'RXG', yearFrom: 1996, yearTo: 1998, variant: '135cc' },
        ],
        oemNumber: '17G-83510-00-YK',
        condition: 'NOS (New Old Stock)',
        partType: 'OEM Original',
        price: 4800,
        originalPrice: 6000,
        quantity: 3,
        negotiable: false,
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
        images: [
          '/parts/speedometer.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: true,
        views: 298,
        rarity: 'Collector Grade',
        shippingAvailable: true,
        shippingCost: 0,
      },
      {
        title: 'Honda City Front Brake Pad Set (OEM Semi-Metallic Compound with Shims)',
        description:
          'Original factory-spec front disc brake pad axle set for 1998-2003 Honda City (Type-Z / SX8). High-friction semi-metallic compound engineered for heat dissipation and zero rotor grooving. Complete with anti-rattle stainless backing shims and acoustic wear indicator clips.',
        category: getCat('brakes-hydraulics'),
        categoryName: 'Brakes & Hydraulics',
        vehicleBrand: 'Honda',
        vehicleModel: 'City Type-Z',
        vehicleYear: 1998,
        vehicleVariant: '1.5 EXi',
        compatibleVehicles: [
          { brand: 'Honda', model: 'City Type-Z', yearFrom: 1998, yearTo: 2003, variant: '1.3 EXi, 1.5 EXi, 1.5 VTEC' },
        ],
        oemNumber: '45022-SX8-T00',
        condition: 'NOS (New Old Stock)',
        partType: 'OEM Original',
        price: 3200,
        originalPrice: 3800,
        quantity: 5,
        negotiable: false,
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
        images: [
          '/parts/brake-pads.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: true,
        views: 185,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 150,
      },
      {
        title: 'Royal Enfield Bullet 350 Heavy Crankshaft & Flywheel Assembly (Made in Redditch Spec)',
        description:
          'Original heavy-weight cast-iron crankshaft assembly for classic Royal Enfield Bullet 350. Delivers the legendary slow, rhythmic "thump" idling cadence. Precision-balanced on dynamic V-blocks with brand new German Torrington connecting rod needle bearings.',
        category: getCat('engine-parts'),
        categoryName: 'Engine Parts',
        vehicleBrand: 'Royal Enfield',
        vehicleModel: 'Bullet 350 (Cast Iron)',
        vehicleYear: 1978,
        vehicleVariant: 'Right-Shift Standard',
        compatibleVehicles: [
          { brand: 'Royal Enfield', model: 'Bullet 350 (Cast Iron)', yearFrom: 1965, yearTo: 2005, variant: 'Cast Iron G2 & B1 Engines' },
        ],
        oemNumber: 'RE-110023-CRK',
        condition: 'OEM Refurbished',
        partType: 'OEM Original',
        price: 14200,
        originalPrice: 16500,
        quantity: 2,
        negotiable: true,
        location: { city: 'Pune', state: 'Maharashtra', pincode: '411004' },
        images: [
          '/parts/crankshaft.jpg',
        ],
        seller: sellerAnand._id,
        status: 'active',
        featured: true,
        views: 290,
        rarity: 'Discontinued OEM',
        shippingAvailable: true,
        shippingCost: 500,
      },
      {
        title: 'Maruti 800 SS80 Original Chrome Honeycomb Front Grille with Logo',
        description:
          'Original first-generation 1983-1986 Maruti 800 (SS80 DX) honeycomb chrome grille with pristine central vintage "M" emblem. Chrome plating is 100% factory original with zero pitting or flaking. All rear mounting tabs and locator pins intact.',
        category: getCat('body-chassis'),
        categoryName: 'Body & Chassis',
        vehicleBrand: 'Maruti Suzuki',
        vehicleModel: '800 (SS80)',
        vehicleYear: 1984,
        vehicleVariant: 'SS80 DX',
        compatibleVehicles: [
          { brand: 'Maruti Suzuki', model: '800 (SS80)', yearFrom: 1983, yearTo: 1986, variant: 'Standard & DX' },
        ],
        oemNumber: 'SZ-71711-78000',
        condition: 'OEM Mint',
        partType: 'OEM Original',
        price: 6200,
        originalPrice: 7500,
        quantity: 1,
        negotiable: true,
        location: { city: 'Pune', state: 'Maharashtra', pincode: '411004' },
        images: [
          '/parts/chrome-grille.jpg',
        ],
        seller: sellerAnand._id,
        status: 'active',
        featured: true,
        views: 215,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 350,
      },
      {
        title: 'Honda City Type-Z 1.5 VTEC OEM Factory High-Rise Rear Spoiler with LED Brake Light',
        description:
          'Rare factory-option high-rise ducktail spoiler with integrated Stanley Japan LED 3rd brake lamp for 2000-2003 Honda City Type-Z (B15C2 VTEC). Finished in original factory Silver Metallic paint. LED light fully tested with crisp illumination. Complete with mounting brackets.',
        category: getCat('body-chassis'),
        categoryName: 'Body & Chassis',
        vehicleBrand: 'Honda',
        vehicleModel: 'City Type-Z',
        vehicleYear: 2001,
        vehicleVariant: '1.5 VTEC',
        compatibleVehicles: [
          { brand: 'Honda', model: 'City Type-Z', yearFrom: 1998, yearTo: 2003, variant: '1.3 EXi, 1.5 EXi, 1.5 VTEC' },
        ],
        oemNumber: '71500-SX8-900',
        condition: 'OEM Mint',
        partType: 'OEM Original',
        price: 9800,
        originalPrice: 12000,
        quantity: 1,
        negotiable: true,
        location: { city: 'New Delhi', state: 'Delhi', pincode: '110001' },
        images: [
          '/parts/rear-spoiler.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: true,
        views: 410,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 450,
      },
      {
        title: 'Yamaha RD350 High Torque (HT) Cylinder Head & Piston Kit (Pair)',
        description:
          'Matched pair of original High Torque (HT) 30.5 BHP spec cylinder heads for Yamaha RD350 twin-cylinder 2-stroke. Professionally glass-bead blasted, de-carbonized, and inspected with zero fin cracks. Included are factory-spec 0.25 oversize pistons with rings and gudgeon pins.',
        category: getCat('engine-parts'),
        categoryName: 'Engine Parts',
        vehicleBrand: 'Yamaha',
        vehicleModel: 'RD350',
        vehicleYear: 1984,
        vehicleVariant: 'High Torque (HT)',
        compatibleVehicles: [
          { brand: 'Yamaha', model: 'RD350', yearFrom: 1983, yearTo: 1989, variant: 'HT & LT' },
        ],
        oemNumber: '360-11111-00-RD',
        condition: 'OEM Refurbished',
        partType: 'OEM Original',
        price: 24500,
        originalPrice: 28000,
        quantity: 1,
        negotiable: false,
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
        images: [
          '/parts/cylinder-piston.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: true,
        views: 620,
        rarity: 'Collector Grade',
        shippingAvailable: true,
        shippingCost: 0,
      },
      {
        title: 'Premier Padmini Vintage Chrome Hubcaps with Fiat Star Emblem (Set of 4)',
        description:
          'Set of 4 pristine condition mirror-finish chrome hubcaps with embossed central Fiat star insignia for Premier Padmini / 1100D steel rims. Complete with spring-tensioned mounting clips. Zero rust spots or denting.',
        category: getCat('wheels-hubs'),
        categoryName: 'Wheels & Hubs',
        vehicleBrand: 'Premier',
        vehicleModel: 'Padmini / Fiat 1100D',
        vehicleYear: 1976,
        vehicleVariant: 'Column Shift',
        compatibleVehicles: [
          { brand: 'Premier', model: 'Padmini / Fiat 1100D', yearFrom: 1964, yearTo: 2000, variant: 'All 14-inch Rim Models' },
        ],
        oemNumber: 'PAL-4091182-HC',
        condition: 'NOS (New Old Stock)',
        partType: 'OEM Original',
        price: 5400,
        originalPrice: 6500,
        quantity: 2,
        negotiable: false,
        location: { city: 'Pune', state: 'Maharashtra', pincode: '411004' },
        images: [
          '/parts/hubcaps.jpg',
        ],
        seller: sellerAnand._id,
        status: 'active',
        featured: true,
        views: 180,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 200,
      },
      {
        title: 'Premier Padmini & Ambassador 7-Inch Round Sealed-Beam Halogen Headlight (Pair)',
        description:
          'Pair of classic 7-inch round convex glass sealed-beam halogen headlamps with period-correct internal parabolic reflectors. Features 12V 60/55W H4 bulbs providing brilliant illumination while retaining 100% authentic vintage styling.',
        category: getCat('lighting-gauges'),
        categoryName: 'Lighting & Gauges',
        vehicleBrand: 'Premier',
        vehicleModel: 'Padmini / Fiat 1100D',
        vehicleYear: 1980,
        vehicleVariant: 'Standard',
        compatibleVehicles: [
          { brand: 'Premier', model: 'Padmini / Fiat 1100D', yearFrom: 1964, yearTo: 2000, variant: 'All 7-inch Bucket Models' },
          { brand: 'Hindustan Motors', model: 'Ambassador', yearFrom: 1970, yearTo: 2005, variant: 'Mark II, III, IV, Classic' },
          { brand: 'Royal Enfield', model: 'Bullet 350 (Cast Iron)', yearFrom: 1965, yearTo: 2005, variant: '7-inch Casquette' },
        ],
        oemNumber: 'AUT-7IN-SB-H4',
        condition: 'NOS (New Old Stock)',
        partType: 'OEM Original',
        price: 2800,
        originalPrice: 3400,
        quantity: 6,
        negotiable: false,
        location: { city: 'Pune', state: 'Maharashtra', pincode: '411004' },
        images: [
          '/parts/headlight.jpg',
        ],
        seller: sellerAnand._id,
        status: 'active',
        featured: true,
        views: 230,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 200,
      },
      {
        title: 'Maruti 800 & Zen Ventilated Disc Brake Rotor (Front Axle Pair)',
        description:
          'Pair of precision-machined cast-iron ventilated front brake disc rotors for Maruti 800 (Type-2/3) and Maruti Zen (1993-2006). Balanced to zero vibration with precision ground friction surface for quiet, fade-free braking performance.',
        category: getCat('brakes-hydraulics'),
        categoryName: 'Brakes & Hydraulics',
        vehicleBrand: 'Maruti Suzuki',
        vehicleModel: '800 (SS80)',
        vehicleYear: 1986,
        vehicleVariant: 'Standard',
        compatibleVehicles: [
          { brand: 'Maruti Suzuki', model: '800 (SS80)', yearFrom: 1983, yearTo: 2014, variant: 'All 800 Models' },
          { brand: 'Maruti Suzuki', model: 'Zen (Carbon/Steel)', yearFrom: 1993, yearTo: 2006, variant: 'All Zen Models' },
        ],
        oemNumber: '55311-70B00',
        condition: 'NOS (New Old Stock)',
        partType: 'OEM Original',
        price: 3400,
        originalPrice: 4200,
        quantity: 4,
        negotiable: false,
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
        images: [
          '/parts/brake-rotor.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: true,
        views: 190,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 250,
      },
      {
        title: 'Mitsubishi Lancer SFXi 4-2-1 Stainless Performance Exhaust Header Manifold',
        description:
          'Period-correct Inox 304 mandrel-bent 4-2-1 equal-length stainless steel performance exhaust header for Mitsubishi Lancer 1.5 4G15 SOHC engine. TIG welded with CNC laser cut flanges. Dyno tested for improved mid-range torque and a crisp vintage rally tone.',
        category: getCat('exhaust-intake'),
        categoryName: 'Exhaust & Intake',
        vehicleBrand: 'Mitsubishi',
        vehicleModel: 'Lancer',
        vehicleYear: 2000,
        vehicleVariant: '1.5 SFXi',
        compatibleVehicles: [
          { brand: 'Mitsubishi', model: 'Lancer', yearFrom: 1998, yearTo: 2006, variant: '1.5 GLXi, 1.5 SFXi' },
        ],
        oemNumber: 'MITS-EXH-4G15-SS',
        condition: 'Used - Grade A',
        partType: 'Period Aftermarket',
        price: 11500,
        originalPrice: 14000,
        quantity: 1,
        negotiable: true,
        location: { city: 'New Delhi', state: 'Delhi', pincode: '110001' },
        images: [
          '/parts/exhaust-header.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: false,
        views: 310,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 400,
      },
      {
        title: 'Maruti Zen (Carbon/Steel) Rare OEM Carbon-Face Speedometer Instrument Cluster',
        description:
          'Ultra-rare original 180 km/h Nippon Denso carbon-weave face gauge cluster from limited-edition 2-door Maruti Zen Carbon. Features integrated tachometer with 7,000 RPM redline, temperature gauge, odometer at 42,110 km, and amber backlit illumination.',
        category: getCat('lighting-gauges'),
        categoryName: 'Lighting & Gauges',
        vehicleBrand: 'Maruti Suzuki',
        vehicleModel: 'Zen (Carbon/Steel)',
        vehicleYear: 2003,
        vehicleVariant: 'Zen Carbon 2-Door',
        compatibleVehicles: [
          { brand: 'Maruti Suzuki', model: 'Zen (Carbon/Steel)', yearFrom: 1993, yearTo: 2006, variant: 'All MPFI & Carb Zen Models' },
        ],
        oemNumber: 'SZ-34100-75F20-CB',
        condition: 'OEM Mint',
        partType: 'OEM Original',
        price: 7800,
        originalPrice: 9500,
        quantity: 1,
        negotiable: false,
        location: { city: 'Pune', state: 'Maharashtra', pincode: '411004' },
        images: [
          '/parts/speedometer.jpg',
        ],
        seller: sellerAnand._id,
        status: 'active',
        featured: true,
        views: 520,
        rarity: 'Collector Grade',
        shippingAvailable: true,
        shippingCost: 250,
      },
      {
        title: 'Maruti Gypsy King AVM Heavy Duty Manual Free-Wheeling 4x4 Hubs (Pair)',
        description:
          'Original Brazilian AVM 438 manual locking front hub pair for Maruti Gypsy King (MG410 & MG413W). Disengages front axle shafts in 2WD mode for reduced drivetrain drag and better fuel economy. 26-spline direct bolt-on with new gaskets.',
        category: getCat('wheels-hubs'),
        categoryName: 'Wheels & Hubs',
        vehicleBrand: 'Maruti Suzuki',
        vehicleModel: 'Gypsy King (MG413W)',
        vehicleYear: 1998,
        vehicleVariant: 'MG413W MPFI 1.3L',
        compatibleVehicles: [
          { brand: 'Maruti Suzuki', model: 'Gypsy King (MG413W)', yearFrom: 1985, yearTo: 2018, variant: 'Narrow & Wide Track 4x4' },
        ],
        oemNumber: 'AVM-438-GYPSY',
        condition: 'Used - Grade A',
        partType: 'Period Aftermarket',
        price: 8900,
        originalPrice: 11000,
        quantity: 1,
        negotiable: true,
        location: { city: 'New Delhi', state: 'Delhi', pincode: '110001' },
        images: [
          '/parts/hubcaps.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: false,
        views: 195,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 300,
      },
      {
        title: 'Bajaj Chetak 150 Complete Chrome Crash Guard Kit with Spare Wheel Carrier',
        description:
          'Heavy gauge chrome-plated tubular body perimeter crash guard kit with rear wrap-around bumper and fold-down luggage rack with spare wheel mount. Triple-nickel chrome coating. Preserved in bubble wrap with no pitting.',
        category: getCat('accessories-badges'),
        categoryName: 'Accessories & Badges',
        vehicleBrand: 'Bajaj',
        vehicleModel: 'Chetak 150',
        vehicleYear: 1988,
        vehicleVariant: '2-Stroke Classic',
        compatibleVehicles: [
          { brand: 'Bajaj', model: 'Chetak 150', yearFrom: 1972, yearTo: 2006, variant: 'Chetak, Super, 150' },
        ],
        oemNumber: 'BAJ-ACC-CGK-150',
        condition: 'NOS (New Old Stock)',
        partType: 'Period Aftermarket',
        price: 3600,
        originalPrice: 4500,
        quantity: 4,
        negotiable: false,
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
        images: [
          '/parts/chrome-grille.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: false,
        views: 140,
        rarity: 'Common Vintage',
        shippingAvailable: true,
        shippingCost: 300,
      },
      {
        title: 'Hindustan Contessa Classic 1.8 GL Isuzu 5-Speed Manual Transmission Gearbox',
        description:
          'Original Isuzu MSG-5K 5-speed overdrive manual transmission box removed from low-mileage 1996 Contessa Classic 1.8 GL. Inspected with smooth syncromesh in all gears including reverse. Bellhousing, clutch fork, and shift lever included.',
        category: getCat('transmission-clutch'),
        categoryName: 'Transmission & Clutch',
        vehicleBrand: 'Hindustan Motors',
        vehicleModel: 'Contessa Classic',
        vehicleYear: 1996,
        vehicleVariant: '1.8 GL Isuzu',
        compatibleVehicles: [
          { brand: 'Hindustan Motors', model: 'Contessa Classic', yearFrom: 1984, yearTo: 2002, variant: '1.8 GL Isuzu 4ZB1' },
        ],
        oemNumber: 'HM-ISZ-5SPD-MSG5K',
        condition: 'Used - Grade A',
        partType: 'OEM Original',
        price: 18500,
        originalPrice: 22000,
        quantity: 1,
        negotiable: true,
        location: { city: 'Pune', state: 'Maharashtra', pincode: '411004' },
        images: [
          '/parts/gearbox.jpg',
        ],
        seller: sellerAnand._id,
        status: 'active',
        featured: false,
        views: 280,
        rarity: 'Discontinued OEM',
        shippingAvailable: true,
        shippingCost: 800,
      },
      {
        title: 'Yezdi Roadking 250 OEM Twin Chrome Fluted Exhaust Mufflers (Pair)',
        description:
          'Pair of factory-original chrome expansion chamber silencer pipes for Ideal Jawa Yezdi Roadking 250. Distinctive fluted trumpet end-caps with removable interior baffles. Deep classic twin-exhaust ring tone.',
        category: getCat('exhaust-intake'),
        categoryName: 'Exhaust & Intake',
        vehicleBrand: 'Yezdi / Jawa',
        vehicleModel: 'Roadking 250',
        vehicleYear: 1991,
        vehicleVariant: 'CB Point',
        compatibleVehicles: [
          { brand: 'Yezdi / Jawa', model: 'Roadking 250', yearFrom: 1978, yearTo: 1996, variant: 'Roadking, CL-II, D250 Classic' },
        ],
        oemNumber: 'YZ-RK-EXH-PR91',
        condition: 'OEM Mint',
        partType: 'OEM Original',
        price: 9200,
        originalPrice: 11000,
        quantity: 2,
        negotiable: false,
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560025' },
        images: [
          '/parts/exhaust-header.jpg',
        ],
        seller: seller._id,
        status: 'active',
        featured: true,
        views: 380,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 350,
      },
      {
        title: 'Lucas-TVS Vintage 12V Ignition Distributor with Vacuum Advance & Rotor',
        description:
          'Original Lucas-TVS 12-Volt mechanical advance distributor with copper contact points and condensator. Tested on distributor strobe machine for smooth timing advance curve. Direct fit for classic Premier Padmini and Ambassador Mark-II/III/IV BMC petrol engines.',
        category: getCat('electrical-ignition'),
        categoryName: 'Electrical & Ignition',
        vehicleBrand: 'Premier',
        vehicleModel: 'Padmini / Fiat 1100D',
        vehicleYear: 1982,
        vehicleVariant: 'Floor Shift S1',
        compatibleVehicles: [
          { brand: 'Premier', model: 'Padmini / Fiat 1100D', yearFrom: 1964, yearTo: 2000, variant: 'All 1100cc Engines' },
          { brand: 'Hindustan Motors', model: 'Ambassador', yearFrom: 1970, yearTo: 1995, variant: '1.5 OHV Petrol' },
        ],
        oemNumber: 'LTVS-40912-DIST',
        condition: 'NOS (New Old Stock)',
        partType: 'OEM Original',
        price: 4800,
        originalPrice: 5800,
        quantity: 3,
        negotiable: false,
        location: { city: 'Pune', state: 'Maharashtra', pincode: '411004' },
        images: [
          '/parts/distributor.jpg',
        ],
        seller: sellerAnand._id,
        status: 'active',
        featured: false,
        views: 165,
        rarity: 'Rare Find',
        shippingAvailable: true,
        shippingCost: 200,
      },
    ]);

    // 4. Create Wanted Parts (Rare Part Sourcing Bounties)
    console.log('Creating vintage parts requests and restorer bounty offers...');
    const wantedPart = await WantedPart.create({
      title: 'Original RD350 HT Left Side Crankcase Cover with Oil Pump Cover',
      description:
        'Looking for an original undamaged left engine clutch casing cover for Yamaha RD350 High Torque. Must have unstripped thread holes and intact oil pump inspection plate.',
      vehicleBrand: 'Yamaha',
      vehicleModel: 'RD350',
      vehicleYear: 1984,
      vehicleVariant: 'High Torque (HT)',
      category: 'Engine Parts',
      targetBudget: 12000,
      urgency: 'urgent',
      conditionRequired: 'NOS Only',
      requester: customer._id,
      status: 'matches_found',
      location: { city: 'Mumbai', state: 'Maharashtra' },
      referenceImages: [
        'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
      ],
      offers: [
        {
          seller: seller._id,
          offerPrice: 11500,
          message:
            'Have a pristine original NOS Japan HT left casing preserved in cosmoline with original oil pump lid. Can ship tomorrow with tracked express freight.',
          createdAt: new Date(),
        },
      ],
    });

    console.log('Catalog seeding complete! Verified realistic inventory & component photography.');
  } catch (err) {
    console.error('Seeder execution error:', err);
  }
};
